M48
; DRILL file {KiCad (6.0.8)} date Thu Dec 29 19:13:58 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-29T19:13:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X64.65Y-33.475
X81.15Y-33.475
X119.05Y-33.5
T2
X26.0Y-28.0
X26.0Y-72.0
X108.0Y-28.0
X108.0Y-72.0
X190.0Y-28.0
X190.0Y-72.0
T0
M30
